### ISSUE TITLE
Scripts not loading

### ISSUE THREAD

**Issue by sebyx07** [azerothcore/acore-docker#40]
Hey, I'm able to start, run and connect to the server, but now I want to customize it and I've added to

`scripts/typescript/index.ts` the content from `scripts/typescript/examples/example.ts`

i've also attached to the container with

`docker attach acore-docker-ac-worldserver-1` and run `reload eluna`

but nothing happens

I've also restarted the containers with `docker-compose down` and up again

**Comment by michaeldelago** [comment]
Can you try adding this section to `docker-compose.override.yaml`:

```yaml
services:
  ac-worldserver:
    environment:
      AC_ELUNA_SCRIPT_PATH: "/azerothcore/env/dist/bin/lua_scripts/scripts"

**Comment by sebyx07** [comment]
cool ty! that worked, but i had to put into docker-compose.yml

**Comment by Helias** [comment]
> Can you try adding this section to `docker-compose.override.yaml`:
> 
> ```yaml
> services:
>   ac-worldserver:
>     environment:
>       AC_ELUNA_SCRIPT_PATH: "/azerothcore/env/dist/bin/lua_scripts/scripts"
> ```

thanks for the suggestion

if this is missing, please add it in the acore-docker repository and/or in the README.md  (then close this issue)

**Comment by jiazufei1** [comment]
> cool ty! that worked, but i had to put into docker-compose.yml

I encountered the same problem, what is the complete content of docker-compose.coverride.yaml after modification? Where should the file be placed?

**Comment by jiazufei1** [comment]
> > Can you try adding this section to `docker-compose.override.yaml`:
> > services:
> >   ac-worldserver:
> >     environment:
> >       AC_ELUNA_SCRIPT_PATH: "/azerothcore/env/dist/bin/lua_scripts/scripts"
> 
> thanks for the suggestion
> 
> if this is missing, please add it in the acore-docker repository and/or in the README.md (then close this issue)

I encountered the same problem, what is the complete content of docker-compose.coverride.yaml after modification? Where should the file be placed?

**Comment by Helias** [comment]
it's not the full content it's just adding a section under services:
```yml
  ac-worldserver:
    environment:
      AC_ELUNA_SCRIPT_PATH: "/azerothcore/env/dist/bin/lua_scripts/scripts"
```
just add this after `ac-db-import-2` section and it should work

**Comment by flhs0606** [comment]
I tried , it didn't work . Here is my docker-compose.override.yaml : 

```
services:
  ac-worldserver:
    volumes:
      - ./conf/worldserver.conf:/azerothcore/env/dist/etc/worldserver.conf
    environment:
      AC_ELUNA_SCRIPT_PATH: "/azerothcore/env/dist/bin/lua_scripts/scripts"

  ac-authserver:
    volumes:
      - ./conf/authserver.conf:/azerothcore/env/dist/etc/authserver.conf

  ac-db-import:
    volumes:
      - ./conf/dbimport.conf:/azerothcore/env/dist/etc/dbimport.conf
```

When I run reload eluna , nothing happens. I don't think eluna is working . How can I solve this problem , thanks!
